services:
  - type: web
    name: online-food-delivery
    runtime: image
    plan: starter
    region: oregon
    image:
      url: ghcr.io/yogeeshinnovates/food-delivery-java_springboot:latest
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: REDIS_HOST
        fromService:
          type: redis
          name: food-delivery-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: food-delivery-redis
          property: port

  - type: redis
    name: food-delivery-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (or restrict to specific IPs if you want tighter security)
